<?php
/* @var $this GestionSolicitudCreditoController */
/* @var $model GestionSolicitudCredito */

$this->breadcrumbs=array(
	'Gestion Solicitud Creditos'=>array('index'),
	$model->id,
);

$this->menu=array(
	array('label'=>'List GestionSolicitudCredito', 'url'=>array('index')),
	array('label'=>'Create GestionSolicitudCredito', 'url'=>array('create')),
	array('label'=>'Update GestionSolicitudCredito', 'url'=>array('update', 'id'=>$model->id)),
	array('label'=>'Delete GestionSolicitudCredito', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage GestionSolicitudCredito', 'url'=>array('admin')),
);
?>

<h1>View GestionSolicitudCredito #<?php echo $model->id; ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'concesionario',
		'vendedor',
		'fecha',
		'modelo',
		'valor',
		'monto_financiar',
		'entrada',
		'year',
		'plazo',
		'taza',
		'cuota_mensual',
		'apellido_paterno',
		'apellido_materno',
		'nombres',
		'cedula',
		'fecha_nacimiento',
		'nacionalidad',
		'estado_civil',
		'empresa_trabajo',
		'telefonos_trabajo',
		'tiempo_trabajo',
		'cargo',
		'direccion_empresa',
		'tipo_relacion_laboral',
		'email',
		'actividad_empresa',
		'apellido_paterno_conyugue',
		'apellido_materno_conyugue',
		'nombres_conyugue',
		'cedula_conyugue',
		'fecha_nacimiento_conyugue',
		'nacionalidad_conyugue',
		'empresa_trabajo_conyugue',
		'telefono_trabajo_conyugue',
		'tiempo_trabajo_conyugue',
		'cargo_conyugue',
		'direccion_empresa_conyugue',
		'tipo_relacion_laboral_conyugue',
		'domicilio_actual',
		'habita',
		'avaluo_propiedad',
		'vive',
		'valor_arriendo',
		'calle',
		'barrio',
		'referencia_domicilio',
		'telefono_residencia',
		'celular',
		'sueldo_mensual',
		'sueldo_mensual_conyugue',
		'banco1',
		'cuenta1',
		'banco2',
		'cuenta2',
		'referencia_personal1',
		'referencia_personal2',
		'parentesco1',
		'parentesco2',
		'telefono_referencia1',
		'telefono_referencia2',
		'activos',
		'pasivos',
		'patrimonio',
		'id_informacion',
		'id_vehiculo',
	),
)); ?>
